#!/usr/bin/env python3
"""
Unofficial RSS feed generator for The Trench Wire
(https://www.trenchcrusade.com/trench-wire/)

Scrapes the article listing page and writes an RSS 2.0 feed to feed.xml.
Designed to be run on a schedule (see .github/workflows/generate-feed.yml).
"""

import re
import sys
from datetime import datetime, timezone
from xml.sax.saxutils import escape

import requests
from bs4 import BeautifulSoup

SOURCE_URL = "https://www.trenchcrusade.com/trench-wire/"
SITE_URL = "https://www.trenchcrusade.com/trench-wire/"
FEED_TITLE = "The Trench Wire (Unofficial Feed)"
FEED_DESCRIPTION = "Unofficial RSS feed for The Trench Wire, generated by scraping the public listing page."
OUTPUT_FILE = "feed.xml"
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
    ),
    "Accept": (
        "text/html,application/xhtml+xml,application/xml;q=0.9,"
        "image/webp,*/*;q=0.8"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}


def fetch_html(url: str) -> str:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return resp.text


def parse_articles(html: str):
    """
    Extract article entries from the 'Latest News' list on the page.
    Each entry is an <a> link whose text contains 'Category • Month Day, Year Title'.
    """
    soup = BeautifulSoup(html, "html.parser")
    articles = []
    seen_urls = set()

    # The "Latest News" list items link directly to /trench-wire/<category>/<slug>/
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "/trench-wire/" not in href:
            continue
        # Skip the section index links themselves
        if href.rstrip("/").endswith("/trench-wire"):
            continue
        if href in seen_urls:
            continue

        text = a.get_text(strip=True)
        if not text:
            continue

        # Typical text pattern: "Hobby • September 4, 2026Creating Slices..."
        match = re.match(
            r"^(?P<category>[A-Za-z]+)\s*•\s*(?P<date>[A-Za-z]+ \d{1,2}, \d{4})(?P<title>.+)$",
            text,
        )
        if not match:
            continue

        category = match.group("category").strip()
        date_str = match.group("date").strip()
        title = match.group("title").strip()

        try:
            pub_date = datetime.strptime(date_str, "%B %d, %Y").replace(
                tzinfo=timezone.utc
            )
        except ValueError:
            continue

        url = href if href.startswith("http") else f"https://www.trenchcrusade.com{href}"
        seen_urls.add(href)

        articles.append(
            {
                "title": title,
                "url": url,
                "category": category,
                "pub_date": pub_date,
            }
        )

    # Newest first
    articles.sort(key=lambda a: a["pub_date"], reverse=True)
    return articles


def build_rss(articles) -> str:
    now = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S %z")

    items_xml = []
    for art in articles:
        pub_date_str = art["pub_date"].strftime("%a, %d %b %Y %H:%M:%S %z")
        items_xml.append(
            f"""    <item>
      <title>{escape(art['title'])}</title>
      <link>{escape(art['url'])}</link>
      <guid isPermaLink="true">{escape(art['url'])}</guid>
      <category>{escape(art['category'])}</category>
      <pubDate>{pub_date_str}</pubDate>
    </item>"""
        )

    items_block = "\n".join(items_xml)

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{escape(FEED_TITLE)}</title>
    <link>{escape(SITE_URL)}</link>
    <description>{escape(FEED_DESCRIPTION)}</description>
    <language>en-us</language>
    <lastBuildDate>{now}</lastBuildDate>
{items_block}
  </channel>
</rss>
"""


def main():
    html = fetch_html(SOURCE_URL)
    articles = parse_articles(html)

    if not articles:
        # Save what we actually received so we can diagnose why parsing
        # failed (e.g. a bot-block/challenge page instead of real content).
        with open("debug_response.html", "w", encoding="utf-8") as f:
            f.write(html)
        print(
            "No articles found. This usually means either the page "
            "structure changed, or the request was blocked/served a "
            "challenge page instead of the real listing. "
            "See debug_response.html (uploaded as a workflow artifact) "
            f"for the raw response. Response length: {len(html)} chars.",
            file=sys.stderr,
        )
        sys.exit(1)

    rss = build_rss(articles)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(rss)

    print(f"Wrote {len(articles)} articles to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
