#!/usr/bin/env python3
"""
Unofficial RSS feed generator for The Trench Wire
(https://www.trenchcrusade.com/trench-wire/)

Scrapes the article listing page and writes an RSS 2.0 feed to feed.xml.
Designed to be run on a schedule (see .github/workflows/generate-feed.yml).
"""

import re
import sys
from datetime import datetime, timezone
from xml.sax.saxutils import escape

import requests
from bs4 import BeautifulSoup

SOURCE_URL = "https://www.trenchcrusade.com/trench-wire/"
SITE_URL = "https://www.trenchcrusade.com/trench-wire/"
FEED_TITLE = "The Trench Wire (Unofficial Feed)"
FEED_DESCRIPTION = "Unofficial RSS feed for The Trench Wire, generated by scraping the public listing page."
OUTPUT_FILE = "feed.xml"
def load_existing_descriptions(path: str):
    """
    Read a previously generated feed.xml (if present) and return a dict of
    {url: (description, image_url)} so we don't re-fetch article pages we
    already have data for.
    """
    cache = {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return cache

    soup = BeautifulSoup(content, "xml")
    for item in soup.find_all("item"):
        link = item.find("link")
        desc = item.find("description")
        image = item.find("enclosure")
        if link and desc:
            cache[link.get_text(strip=True)] = (
                desc.get_text(),
                image["url"] if image and image.has_attr("url") else None,
            )
    return cache


def fetch_article_preview(url: str):
    """
    Fetch an individual article page and pull its meta description and
    featured image, used for the RSS <description> and <enclosure>.
    Returns (description, image_url); either may be None on failure.
    """
    try:
        html = requests.get(url, headers=HEADERS, timeout=30).text
    except requests.RequestException:
        return None, None

    soup = BeautifulSoup(html, "html.parser")

    description = None
    og_desc = soup.find("meta", attrs={"property": "og:description"})
    if og_desc and og_desc.get("content"):
        description = og_desc["content"].strip()
    else:
        meta_desc = soup.find("meta", attrs={"name": "description"})
        if meta_desc and meta_desc.get("content"):
            description = meta_desc["content"].strip()

    image_url = None
    og_image = soup.find("meta", attrs={"property": "og:image"})
    if og_image and og_image.get("content"):
        image_url = og_image["content"].strip()

    return description, image_url


HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
    ),
    "Accept": (
        "text/html,application/xhtml+xml,application/xml;q=0.9,"
        "image/webp,*/*;q=0.8"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}


def fetch_html(url: str) -> str:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return resp.text


def parse_articles(html: str):
    """
    Extract article entries from the 'Latest News' list on the page.
    Each entry is an <a> link whose text contains 'Category • Month Day, Year Title'.
    """
    soup = BeautifulSoup(html, "html.parser")
    articles = []
    seen_urls = set()

    # The "Latest News" list items link directly to /trench-wire/<category>/<slug>/
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "/trench-wire/" not in href:
            continue
        # Skip the section index links themselves
        if href.rstrip("/").endswith("/trench-wire"):
            continue
        if href in seen_urls:
            continue

        text = a.get_text(strip=True)
        if not text:
            continue

        # Typical text pattern: "Hobby • September 4, 2026Creating Slices..."
        match = re.match(
            r"^(?P<category>[A-Za-z]+)\s*•\s*(?P<date>[A-Za-z]+ \d{1,2}, \d{4})(?P<title>.+)$",
            text,
        )
        if not match:
            continue

        category = match.group("category").strip()
        date_str = match.group("date").strip()
        title = match.group("title").strip()

        try:
            pub_date = datetime.strptime(date_str, "%B %d, %Y").replace(
                tzinfo=timezone.utc
            )
        except ValueError:
            continue

        url = href if href.startswith("http") else f"https://www.trenchcrusade.com{href}"
        seen_urls.add(href)

        articles.append(
            {
                "title": title,
                "url": url,
                "category": category,
                "pub_date": pub_date,
            }
        )

    # Newest first
    articles.sort(key=lambda a: a["pub_date"], reverse=True)
    return articles


def build_rss(articles) -> str:
    now = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S %z")

    items_xml = []
    for art in articles:
        pub_date_str = art["pub_date"].strftime("%a, %d %b %Y %H:%M:%S %z")
        description = art.get("description") or art["title"]
        enclosure = ""
        if art.get("image_url"):
            enclosure = f'\n      <enclosure url="{escape(art["image_url"])}" type="image/webp"/>'
        items_xml.append(
            f"""    <item>
      <title>{escape(art['title'])}</title>
      <link>{escape(art['url'])}</link>
      <guid isPermaLink="true">{escape(art['url'])}</guid>
      <category>{escape(art['category'])}</category>
      <pubDate>{pub_date_str}</pubDate>
      <description>{escape(description)}</description>{enclosure}
    </item>"""
        )

    items_block = "\n".join(items_xml)

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>{escape(FEED_TITLE)}</title>
    <link>{escape(SITE_URL)}</link>
    <description>{escape(FEED_DESCRIPTION)}</description>
    <language>en-us</language>
    <lastBuildDate>{now}</lastBuildDate>
{items_block}
  </channel>
</rss>
"""


def main():
    html = fetch_html(SOURCE_URL)
    articles = parse_articles(html)

    if not articles:
        # Save what we actually received so we can diagnose why parsing
        # failed (e.g. a bot-block/challenge page instead of real content).
        with open("debug_response.html", "w", encoding="utf-8") as f:
            f.write(html)
        print(
            "No articles found. This usually means either the page "
            "structure changed, or the request was blocked/served a "
            "challenge page instead of the real listing. "
            "See debug_response.html (uploaded as a workflow artifact) "
            f"for the raw response. Response length: {len(html)} chars.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Reuse descriptions/images we already fetched on a previous run so we
    # don't re-hit every article page on every hourly run.
    cache = load_existing_descriptions(OUTPUT_FILE)

    for art in articles:
        cached = cache.get(art["url"])
        if cached:
            art["description"], art["image_url"] = cached
        else:
            description, image_url = fetch_article_preview(art["url"])
            art["description"] = description
            art["image_url"] = image_url

    rss = build_rss(articles)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(rss)

    print(f"Wrote {len(articles)} articles to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
